apiVersion: apps/v1
kind: Deployment
metadata:
  name: geolocation-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geolocation-service
  template:
    metadata:
      labels:
        app: geolocation-service
    spec:
      containers:
      - name: geolocation-service
        image: adityag743/geolocation-service
        env:
        - name: RABBITMQ_HOST
          value: "rabbitmq"  # Ensure this matches the Service name
        - name: RABBITMQ_PORT
          value: "5672"
---
apiVersion: v1
kind: Service
metadata:
  name: geolocation-service
spec:
  selector:
    app: geolocation-service
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672
